env: traffic_junction

env_args:
  map_name: traffic_junction_easy
  nagents: 5
  display: False
  dim: 6
  vision: 0
  add_rate_min: 0.1
  add_rate_max: 0.3
  curr_start: 0
  curr_end: 0
  difficulty: "easy"
  vocab_type: "bool"
  time_limit: 20

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 4050000
test_interval: 5000
test_nepisode: 32